development:
  adapter: postgresql
  encoding: unicode
  database: cat_training_course_development
  pool: 5
  username: <%= ENV['PG_DB_USER'] %>
  password: <%= ENV["PG_DB_PW"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: cat_training_course_test
  pool: 5
  username: <%= ENV["PG_DB_USER"] %>
  password: <%= ENV["PG_DB_PW"] %>